// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var EncryptionFailure = Caml_exceptions.create("Password_error.EncryptionFailure");

var NotImplemented = Caml_exceptions.create("Password_error.NotImplemented");

var UknownFailure = Caml_exceptions.create("Password_error.UknownFailure");

exports.EncryptionFailure = EncryptionFailure;
exports.NotImplemented = NotImplemented;
exports.UknownFailure = UknownFailure;
/* No side effect */
