// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Password_async = require("./Password_async.bs.js");

function deriveKey(algorithm, input) {
  return new Promise((function (resolve, _) {
                return Password_async.deriveKey(algorithm, input, (function (x) {
                              return resolve(x);
                            }));
              }));
}

function verify(algorithm, key, input) {
  return new Promise((function (resolve, _) {
                return Password_async.verify(algorithm, key, input, (function (x) {
                              return resolve(x);
                            }));
              }));
}

function token(algorithm, length) {
  return new Promise((function (resolve, _) {
                return Password_async.token(algorithm, length, (function (x) {
                              return resolve(x);
                            }));
              }));
}

exports.deriveKey = deriveKey;
exports.verify = verify;
exports.token = token;
/* Password_async Not a pure module */
