// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Future = require("reason-future/src/Future.bs.js");
var Password_async = require("./Password_async.bs.js");

function deriveKey(algorithm, input) {
  return Future.make((function (resolve) {
                return Password_async.deriveKey(algorithm, input, Curry.__1(resolve));
              }));
}

function verify(algorithm, key, input) {
  return Future.make((function (resolve) {
                return Password_async.verify(algorithm, key, input, Curry.__1(resolve));
              }));
}

function token(algorithm, length) {
  return Future.make((function (resolve) {
                return Password_async.token(algorithm, length, Curry.__1(resolve));
              }));
}

exports.deriveKey = deriveKey;
exports.verify = verify;
exports.token = token;
/* Password_async Not a pure module */
