// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function fromString(x) {
  switch (x) {
    case "bcrypt" : 
        return /* Bcrypt */0;
    case "scrypt" : 
        return /* Scrypt */1;
    default:
      return Pervasives.failwith("invalid_algorithm");
  }
}

function toString(param) {
  if (param) {
    return "scrypt";
  } else {
    return "bcrypt";
  }
}

exports.fromString = fromString;
exports.toString = toString;
/* No side effect */
